_extends: sakupi01.com:.github/release-drafter-base.yml
name-template: git-green-cli@$RESOLVED_VERSION
tag-template: git-green-cli@$RESOLVED_VERSION
tag-prefix: git-green-cli@
include-paths:
  - "packages/git-green-cli/"
template: |
  ## [git-green-cli@$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
  ## Changes
  $CHANGES
